
import java.util.LinkedHashMap;
import java.util.Map;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author PC
 */
public class SiparisUygulamasi extends javax.swing.JFrame {

    //Map kullanmamızın sebebi aynı keyworde ait bir veriyi ikinci defa eklemeyi engellemek.
    //Bu sayede tekrarı engellemiş olduk.
    Map<String, Integer> siparisMap = new LinkedHashMap<String, Integer>();

    /**
     * Creates new form SiparisUygulamasi
     */
    public SiparisUygulamasi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        checkIskender = new javax.swing.JCheckBox();
        checkSalata = new javax.swing.JCheckBox();
        checkAyran = new javax.swing.JCheckBox();
        checkBeyti = new javax.swing.JCheckBox();
        btnSiparisGoster = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setText("MENÜ");

        checkIskender.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        checkIskender.setText("İskender - 15 TL");

        checkSalata.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        checkSalata.setText("Salata - 5 TL");

        checkAyran.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        checkAyran.setText("Ayran - 2 TL");

        checkBeyti.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        checkBeyti.setText("Beyti - 12 TL");

        btnSiparisGoster.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSiparisGoster.setText("Siparişleri Göster");
        btnSiparisGoster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiparisGosterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSiparisGoster, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(checkAyran)
                    .addComponent(checkBeyti)
                    .addComponent(checkSalata)
                    .addComponent(checkIskender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1))
                .addContainerGap(127, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkIskender)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkBeyti)
                .addGap(3, 3, 3)
                .addComponent(checkSalata)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkAyran)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSiparisGoster, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(153, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void siparisleriGoster() {

        String mesaj = "";
        int tutar = 0;
        if (!siparisMap.isEmpty()) {
            
            mesaj +="Siparişleriniz ;\n";
            
            for(Map.Entry<String,Integer> entry : siparisMap.entrySet()){
                
                mesaj += entry.getKey()+"\n";
                tutar += entry.getValue();
                
            }
            mesaj +="Toplam Tutar : "+tutar;
            
        }
        else {
            mesaj = "Siparişiniz bulunmamaktadır.";
        }
        
        JOptionPane.showMessageDialog(this, mesaj);
        
    }

    private void btnSiparisGosterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiparisGosterActionPerformed

        if (checkIskender.isSelected()) {

            siparisMap.put("İskender", 15);

        } else {

            siparisMap.remove("İskender");

        }
        if (checkBeyti.isSelected()) {

            siparisMap.put("Beyti", 12);

        } else {

            siparisMap.remove("Beyti");

        }
        if (checkSalata.isSelected()) {

            siparisMap.put("Salata", 5);

        } else {

            siparisMap.remove("Salata");

        }
        if (checkAyran.isSelected()) {

            siparisMap.put("Ayran", 2);

        } else {

            siparisMap.remove("Ayran");

        }

        siparisleriGoster();


    }//GEN-LAST:event_btnSiparisGosterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SiparisUygulamasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SiparisUygulamasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SiparisUygulamasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SiparisUygulamasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SiparisUygulamasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSiparisGoster;
    private javax.swing.JCheckBox checkAyran;
    private javax.swing.JCheckBox checkBeyti;
    private javax.swing.JCheckBox checkIskender;
    private javax.swing.JCheckBox checkSalata;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
